### ISSUE TITLE
[Feature request] Allow tex formatting in multiline code blocks 

### ISSUE THREAD

**Issue by BarioIsCoding** [BinaryQuantumSoul/discord-latex#2]
I can't seem to find out how to use multiline LaTeX code.. any way to fix this?

**Comment by BinaryQuantumSoul** [comment]
Can you give example of what you are trying to do?
As you can see [here](https://tex.stackexchange.com/questions/46189/how-do-i-add-a-line-break-in-display-math-mode), you can try using a gather or an align environment.

For example:
`` `$$\begin{gather}
    a + b = c \\ 
    a = c - b
\end{gather}$$` ``
`` `$$\begin{align}
    a + b &= c \\        
    a &= c - b
\end{align}$$` ``

**Comment by clragon** [comment]
I assume they mean multiline codeblocks, with triple backticks.
that would be a great feature to have!

**Comment by BinaryQuantumSoul** [comment]
Can you give an example of a useful usage ?

**Comment by clragon** [comment]
Its nicer to read and edit:

```
\```$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$\```
```

than with single quotes (especially for other people who dont have the plugin).
