### ISSUE TITLE
CSS injection

### ISSUE THREAD

**Issue by eMGeeneer** [BinaryQuantumSoul/discord-latex#3]
It is possible to perform CSS injection with the same technique as was used on github.
For example: `$$\ce{$\unicode[goombafont;cursor: all-scroll;]{x0000}$}$$` will create a box where the cursor changes icons

https://github.com/BinaryQuantumSoul/discord-latex/assets/145163394/15e376cc-5c05-4801-8b8c-832f38369420

**Comment by BinaryQuantumSoul** [comment]
Thank you!

Temporary fix by removing `\unicode` from all tex codes, since it's hardly ever used.
Tell me if you have a more long term fix idea.
