### ISSUE TITLE
Any plans of expanding this to mobile like with Enmity?

### ISSUE THREAD

**Issue by Suds-p** [BinaryQuantumSoul/discord-latex#5]
This plugin is super useful to me and I'm wondering if there's an equivalent for the mobile Discord clients or if there's any plans to support mobile in the future.

**Comment by BinaryQuantumSoul** [comment]
Great to know that you like it :)
Unfortunately the discord mobile client is completely different than BetterDiscord which uses JavaScript (like mathjax). Probably doable with a java aliucord plugin but I have absolutely no idea how

**Comment by BinaryQuantumSoul** [comment]
Looks like Enmity is made for ios anyway. I only do Linux and Android projects. But looking at it the Enmity plugins are Typescript so this plugin could maybe be ported indeed
